-- MySQL Script generated by MySQL Workbench
-- Mon Sep  9 07:19:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AgendaTurbo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AgendaTurbo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AgendaTurbo` DEFAULT CHARACTER SET utf8 ;
USE `AgendaTurbo` ;

-- -----------------------------------------------------
-- Table `AgendaTurbo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgendaTurbo`.`usuario` (
  `usu_cod` INT NOT NULL AUTO_INCREMENT,
  `usu_nome` VARCHAR(45) NULL,
  `usu_email` VARCHAR(45) NULL,
  `usu_login` VARCHAR(45) NULL,
  `usu_senha` VARCHAR(45) NULL,
  PRIMARY KEY (`usu_cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgendaTurbo`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AgendaTurbo`.`contato` (
  `con_cod` INT NOT NULL AUTO_INCREMENT,
  `con_nome` VARCHAR(95) NULL,
  `con_rua` VARCHAR(95) NULL,
  `con_bairro` VARCHAR(45) NULL,
  `con_complemento` VARCHAR(45) NULL,
  `con_cep` VARCHAR(45) NULL,
  `con_estado` VARCHAR(45) NULL,
  `con_cidade` VARCHAR(45) NULL,
  `con_email` VARCHAR(45) NULL,
  `con_telefone` VARCHAR(45) NULL,
  `con_celular` VARCHAR(45) NULL,
  `usu_cod` INT NOT NULL,
  PRIMARY KEY (`con_cod`),
  INDEX `fk_contato_usuario_idx` (`usu_cod` ASC),
  CONSTRAINT `fk_contato_usuario`
    FOREIGN KEY (`usu_cod`)
    REFERENCES `AgendaTurbo`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
